version: "2"
services:
  shell:
    image: eduardoshanahan/openssh:latest
    container_name: es_openssh
    volumes:
      - ./keys:/keys
    working_dir: /keys
    entrypoint:
      - ssh-keygen

  data-container:
    image: eduardoshanahan/openssh:latest
    container_name: openssh_data
    volumes:
      - ./keys:/keys
