version: "3.4"

services:

  shell:
    image: eduardoshanahan/openssh:latest
    container_name: es_openssh
    volumes:
      - type: bind
        source: .
        target: /root/.ssh/
    entrypoint:
      - /bin/sh

